# -*- coding: utf-8 -*-
"""NER Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mz7S1fEHQMdqToaiAZiKTDbX6Mv1z_G8
"""

# Python program to convert a list to string 
    
# Function to convert   
def listToString(s):  
    
    # initialize an empty string 
    str1 = ""  
    
    # traverse in the string   
    for ele in s:  
        str1 += ele   
    
    # return string   
    return str1

import spacy

# Load English tokenizer, tagger, parser, NER and word vectors
nlp = spacy.load("en_core_web_sm")

# Process whole documents
text = ("This is to certify that Yash Gupta was vaccinated on 26th January 2020 in Hong Kong at The Evangel Hospital. He took the brand Moderna vaccine")

wordList = text.split()
print(wordList)
brand = wordList[wordList.index('brand')+1]

doc = nlp(text)


# Analyze syntax

result = {}
# Find named entities, phrases and concepts
for entity in doc.ents:
    #print(entity.text, entity.label_)
    if ((entity.label_ == 'GPE') or (entity.label_ == 'ORG')):
      continue
    result[entity.label_] = []

for entity in doc.ents:
    #print(entity.text, entity.label_)
    if ((entity.label_ == 'GPE') or (entity.label_ == 'ORG')):
      continue
    result[entity.label_].append(entity.text)
result['Brand'] = [brand]
print(result)

